version: '3'
services:
  etcd0:
    volumes:
      - ~/dockerdata/etcdssl:/etc/etcd/etcdSSL
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd0:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd0:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem 
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem 
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem 
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem 
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem 
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem 
  etcd1:
    volumes:
      - ~/dockerdata/etcdssl:/etc/etcd/etcdSSL
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd1:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd1:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem
  etcd2:
    volumes:
      - ~/dockerdata/etcdssl:/etc/etcd/etcdSSL
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd2:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd2:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/ca.pem
