listen = ":3000"
debug = true
etcd_root_key = "root"
etcd_addr = ["127.0.0.1:12379"]
etcd_version =  "v3"
etcd_watch = true
etcd_back_path = "./etcd_bak"
etcd_back_time = "0 0 0 * * *"
history_num = 10
history_really_del = true
service_name = "etcd_browser"
log_dir = "./log"
log_type_json =  true


[db]
source_name = "./.etcd_browser"